### ISSUE TITLE
How to eval the models

### ISSUE THREAD

**Issue by Yeeesir** [Vance0124/Token-level-Direct-Preference-Optimization#4]
Excuse me, does this repository contain scripts for model inference evaluation?

**Comment by Vance0124** [comment]
Sorry, due to our current workload on other projects, we haven't had time to organize the evaluation scripts yet. We will gradually release the evaluation code soon. In the meantime, you can first refer to the evaluation code of f-DPO: https://github.com/alecwangcq/f-divergence-dpo, which we initially referenced for the evaluations in our paper. Thank you very much for your understanding.
